---
title: "NonWork"
author: "Maitreya Wagh"
date: "6/3/2018"
output:
  html_document:
    keep_md: yes
---

```{r}
library(ggplot2)
Person <- read.csv("../data/vista/2018-05-23-vista-2013-16/VISTA_2012_16_v1_SA1_CSV/P_VISTA12_16_SA1_V1.csv")
Work <- read.csv("../data/vista/2018-05-23-vista-2013-16/VISTA_2012_16_v1_SA1_CSV/JTW_VISTA12_16_SA1_V1.csv")
Person <- Person[,c(1,8,9,10,11,16,17,18,19,25,27,24,23)]


```

```{r}
Person <- Person[Person$PERSID %in% Work$PERSID, ]
SingWrkPerson <- subset(as.data.frame(table(Work$PERSID)), as.data.frame(table(Work$PERSID))$Freq == 1)
SingWrk <- Work[Work$PERSID %in% SingWrkPerson$Var1,]
SingWrkPerson <- Person[Person$PERSID %in% SingWrkPerson$Var1,]
SingWrk <- cbind(SingWrk,SingWrkPerson)
disp <- SingWrk[, c(1,4,7,9,10,11,12,14,16,17,19,20,21,22,23,32,41,77,79,80,83,108:119)]
```

```{r}
Person <- Person[Person$PERSID %in% Work$PERSID, ]
MultWrkPerson <- subset(as.data.frame(table(Work$PERSID)), as.data.frame(table(Work$PERSID))$Freq > 1)
MultWrk <- Work[Work$PERSID %in% MultWrkPerson$Var1,]
MultWrkPerson <- Person[Person$PERSID %in% MultWrkPerson$Var1,]
```
Lot of random data here. Some babies and children are said to go their own wordplace, but are not in the work force. Let us only talk about people in the workforce now. 
```{r}
SingWrk <- (SingWrk[SingWrk$ANYWORK != "No"|SingWrk$ANZSCO1!="Not in Work Force",])
table(SingWrk$PURP1)
SingWrk$TtW[SingWrk$PURP1 == "Work Related"]<- "Direct"
SingWrk$TtW[SingWrk$PURP1 != "Work Related"]<- "Indirect"
pub <- subset(SingWrk[(SingWrk$JTWMODE != "Vehicle Driver"& SingWrk$JTWMODE != "Vehicle Passenger" & SingWrk$JTWMODE!= "Walking"),])
priv <- subset(SingWrk[(SingWrk$JTWMODE == "Vehicle Driver"|SingWrk$JTWMODE == "Vehicle Passenger" | SingWrk$JTWMODE== "Walking"),])
```

```{r, fig.width=15, fig.height=10}
ggplot(SingWrk, aes(x=SingWrk$TRAVDOW, fill = SingWrk$SEX)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x=SingWrk$TRAVDOW, fill = SingWrk$TtW)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
SingWrk$STARTHOUR <- as.factor(SingWrk$STARTHOUR)
ggplot(SingWrk, aes(x=SingWrk$TRAVDOW, fill = SingWrk$STARTHOUR)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
table(SingWrk$STARTHOUR)
table(SingWrk$SEX, SingWrk$TtW)

ggplot(SingWrk, aes(x=SingWrk$STARTHOUR, fill = SingWrk$SEX)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x=SingWrk$STARTHOUR, fill = SingWrk$TtW)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(SingWrk, aes(x=SingWrk$JTWMODE, fill = SingWrk$TtW)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(SingWrk, aes(x=SingWrk$ANZSCO1, fill = SingWrk$SEX)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x=SingWrk$ANZSCO1, fill = SingWrk$STARTHOUR)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(pub, aes(x=pub$ANZSCO1, fill = pub$JTWMODE)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(pub, aes(x=pub$TRAVDOW, fill = pub$JTWMODE)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(priv, aes(x=priv$ANZSCO1, fill = priv$JTWMODE)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(priv, aes(x=priv$TRAVDOW, fill = priv$JTWMODE)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(SingWrk, aes(x=SingWrk$ANZSCO1, fill = SingWrk$AGEGROUP)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
table(SingWrk$ANZSCO1, SingWrk$AGEGROUP)
tab2<-table(SingWrk$ANZSCO1, SingWrk$JTWMODE)
prop.table(tab2,1)

```


df

```{r, fig.width=15, fig.height=10}
ggplot(SingWrk, aes(x = SingWrk$TRAVDOW, y = SingWrk$STARTIME, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$STARTIME, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$STARTIME, fill = SingWrk$TtW )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$ANZSCO1, y = SingWrk$STARTIME, fill = SingWrk$SEX )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```
Do same for Depature time, and duration

Public/Private division. Find distributions.

Relationship/TravelPeriod, Type of Work also factors. 



```{r, fig.width=15, fig.height=10}

SingWrk$DEPTIME <- as.integer(SingWrk$DEPTIME)
SingWrk$DEPHOUR <- as.integer(SingWrk$DEPHOUR)


ggplot(SingWrk, aes(x = SingWrk$TRAVDOW, y = SingWrk$DEPTIME, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$DEPTIME, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$DEPTIME, fill = SingWrk$TtW )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$ANZSCO1, y = SingWrk$DEPTIME, fill = SingWrk$SEX )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))


ggplot(SingWrk, aes(x = SingWrk$TRAVDOW, y = SingWrk$DEPHOUR, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$DEPHOUR, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$ANZSCO1, y = SingWrk$DEPHOUR, fill = SingWrk$SEX )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```



```{r, fig.width=15, fig.height=10}
SingWrk$workDuration <- as.integer(SingWrk$workDuration)
ggplot(SingWrk, aes(x = SingWrk$TRAVDOW, y = SingWrk$workDuration, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$AGEGROUP, y = SingWrk$workDuration, fill = SingWrk$SEX)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(SingWrk, aes(x = SingWrk$ANZSCO1, y = SingWrk$workDuration, fill = SingWrk$SEX )) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```
